### ISSUE TITLE
VoiceModule.startSpeech(): Support for setting intent parameters

### ISSUE THREAD

**Issue by kev-slater-mhr** [wenkesj/react-native-voice#10]
Any possibility of adding support for setting intent parameters like:
•	EXTRA_SPEECH_INPUT_COMPLETE_SILENCE_LENGTH_MILLIS
•	EXTRA_SPEECH_INPUT_MINIMUM_LENGTH_MILLIS
•	EXTRA_SPEECH_INPUT_POSSIBLY_COMPLETE_SILENCE_LENGTH_MILLIS

...in VoiceModule.startSpeech() in order to control things such as the length of the speech capture?

**Comment by wenkesj** [comment]
I appreciate the feedback and the opinion here. I don't have much time to maintain this repository alone, so any improvements can be made from others. But I can point you to a similar API that does expose intent and has a very similar Java-like API, [here](https://github.com/de-code/react-native-android-speech-recognizer) :). Sorry for the inconvenience, and any help/involvement is appreciated!

**Comment by kev-slater-mhr** [comment]
Thanks for the feedback!
