### ISSUE TITLE
Attempt to invoke virtual method 'void android.speech.SpeechRecognizer.destroy()' on a null object reference on Android

### ISSUE THREAD

**Issue by davychhouk** [wenkesj/react-native-voice#104]
<img width="694" alt="screen shot 2561-06-11 at 11 51 54" src="https://user-images.githubusercontent.com/13924709/41213371-22020af6-6d6f-11e8-9515-037db72b7806.png">

**Comment by pohsiu** [comment]
which means it can't find your voice instance to destroy,
you must destroy after start

**Comment by davychhouk** [comment]
@pohsiu Yes.
