### ISSUE TITLE
Force Close when start record

### ISSUE THREAD

**Issue by achigo16** [wenkesj/react-native-voice#108]
When start recording, RN hang and after that it exits automatically

    "react": "16.4.1",
    "react-native": "0.56.0",
    "react-native-voice": "^0.2.6",

**Comment by szholdiyarov** [comment]
can you share your logs please? 
does it happen on IOS or Android or both?

**Comment by redant23** [comment]
I got same issue too 
    "react": "16.4.1",
    "react-native": "0.56.0",
    "react-native-voice": "^0.2.6"

**Comment by achigo16** [comment]
@szholdiyarov there is no log showing because exits automatically.

**Comment by sibelius** [comment]
get native crash log, without this is impossible to debug
