### ISSUE TITLE
dyld_sim`dyld_fatal_error on ios 9.1.2

### ISSUE THREAD

**Issue by tiennguyen9988** [wenkesj/react-native-voice#110]
![screen shot 2018-07-19 at 11 18 48 am 3](https://user-images.githubusercontent.com/3782474/42921326-b80ecc48-8b45-11e8-936e-c1e6ed1d0d55.png)
dyld: Library not loaded: /System/Library/Frameworks/Speech.framework/Speech
  Referenced from: /Users/beonline2/Library/Developer/CoreSimulator/Devices/5B5D8349-5F7B-43EE-9ED0-B7182BDE48ED/data/Containers/Bundle/Application/DF9605BD-7B96-4119-913A-24262A667D4A/rnapp.app/rnapp
  Reason: image not found
Please help me!

**Comment by sibelius** [comment]
upgrade to ios10
