### ISSUE TITLE
Random error after upgraded to 0.2.6 and React-Native 0.56.0

### ISSUE THREAD

**Issue by ithieund** [wenkesj/react-native-voice#115]
Hi, I'm facing with this issue.
I worked previously but after upgrading the library to latest version and React-Native to version 0.56.0, all tries end with error, the message is random

> 08-11 01:03:20.492  6655 16161 I ReactNativeJS: { error: { message: '2/Network error' } }
> 08-11 01:03:22.074  6655 16161 I ReactNativeJS: { error: { message: '2/Network error' } }
> 08-11 01:03:40.221  6655 16161 I ReactNativeJS: { error: { message: '5/Client side error' } }
> 08-11 01:03:41.939  6655 16161 I ReactNativeJS: { error: { message: '5/Client side error' } }
> 08-11 01:03:50.311  6655 16161 I ReactNativeJS: { error: { message: '2/Network error' } }
> 08-11 01:04:10.218  6655 16161 I ReactNativeJS: { error: { message: '5/Client side error' } }
> 08-11 01:07:26.908  6655 16161 I ReactNativeJS: { error: { message: '2/Network error' } }
> 08-11 01:07:46.789  6655 16161 I ReactNativeJS: { error: { message: '5/Client side error' } }

Can anyone help?
Thanks.

**Comment by NoahDragon** [comment]
Got the same errors on Android, but works well on iOS.

**Comment by meiqi1992** [comment]
+1 @ithieund  how to do it?

**Comment by meiqi1992** [comment]
need help

**Comment by Blacktoviche** [comment]
It's the same here on Android. It keeps producing Error: { message: '2/Network error'}, when pressing record button
Any solution ?
Here is a screenshot
![screenshot_1539604198](https://user-images.githubusercontent.com/16650583/46949412-09022580-d08a-11e8-94df-fab6c1d05ad8.png)

**Comment by arshbhatti8** [comment]
I have the same errors.

**Comment by Blacktoviche** [comment]
It works now, The problem was permission and simulator,
I bundled my test app and run it on Android device,
Also granted microphone permission for Google app and now everything is ok

**Comment by arshbhatti8** [comment]
@Blacktoviche can you please drop in more details. I'm on a time crunch here, really need this to work.

Did you install the app on an actual android phone instead of an emulator?

**Comment by Blacktoviche** [comment]
@arshbhatti8  Yes I installed the app example on actual device. and it works perfect.

**Comment by arshbhatti8** [comment]
It works for on an actual phone ! Still doesn't work on an emulator. @Blacktoviche  Thanks !

**Comment by sibelius** [comment]
use PermissionsAndroid to ask for RECORD_AUDIO permission before start voice recognition
