### ISSUE TITLE
The VoiceTest example does not work in ios simulator 

### ISSUE THREAD

**Issue by jeremygottfried** [wenkesj/react-native-voice#118]
This is probably a ReadMe issue more than an actual bug, but I cannot get the given example to work.
I cloned the VoiceTest repo: https://github.com/wenkesj/react-native-voice/tree/master/VoiceTest

I ran `npm install` , `npm install -save react-native-voice`, `react-native link react-native-voice` and `npm start` 

However, `react-native run-ios` doesn't work. 

The error is: ":CFBundleIdentifier", does not exist. 

How do I get the example up and running?

**Comment by danielsellergren** [comment]
Able to replicate this with a fresh clone as well.

I was able to get the application running by creating a new React Native project from their [tutorial](https://facebook.github.io/react-native/docs/getting-started.html) (I used the part for Building Projects with Native Code, not sure if it's relevant). I kept the `index.js` file the same as the default when creating the project, and moved the example code from the `index.js` file in this project to my `App.js`. This got the project up and running for me.

**Comment by jeremygottfried** [comment]
Thanks, I will try this in the next couple of days to see if it solves the issue on my end.

**Comment by jeremygottfried** [comment]
Ok I finally got the given example to work. 
Here are the steps: 
1. `create-react-app VoiceNative`
2. `cd VoiceNative`
2.  `npm run eject` 
3. `npm i react-native-voice --save`
4. `react-native link react-native-voice`
5. Copy the code from VoiceTest/index.js to the app.js file in the VoiceNative directory
6. copy the button.png file to my root directory. 
7. Copy the following to build/VoiceNative/Info.plist: 
	`<key>NSMicrophoneUsageDescription</key>`
 `<string>Description of why you require the use of the microphone</string>`
 `<key>NSSpeechRecognitionUsageDescription</key>`
 `<string>Description of why you require the use of the speech recognition</string>`
8. `react-native run-ios`

**Comment by sibelius** [comment]
we need to upgrade example to latest react native version

**Comment by afacar** [comment]
I have the similar issue with Android emulator. I install the library (`npm i react-native-voice --save`) and link it automatically (`react-native link react-native-voice`) in the existing project. But when I do `react-native run-android` I get this error: **objects are not valid as a react child (found object with keys {$$typeof type key ref props _owner _store}). If you meant to render a collection of children, use an array instead.**  I checked internet for this error, they are mostly related to importing the correct firebase version etc. But in my case, project was already working until I install the library. Any help is appreaciated!
