### ISSUE TITLE
Error with library react native navigation

### ISSUE THREAD

**Issue by bytesk** [wenkesj/react-native-voice#129]
hei dude, i'm get some error  which is i'm use react native navigation 
because setting react native navigation change MainActivity.java and MainApplication.java for extends 

react native voice need extends ReactActivity, in react native navigation no need this and extends other,

this i attach img for example error, after i klik start button react native voice i got this error.

i hope u reply my post, thanks 

![photo_2018-10-18_15-24-53](https://user-images.githubusercontent.com/36951004/47152340-9fdb1600-d306-11e8-9150-1b7c6bed036b.jpg)

**Comment by bytesk** [comment]
im done

**Comment by DanielBoening** [comment]
How did you solve it? Can you share your solution?

**Comment by bytesk** [comment]
> how did you solve it? Can you share your solution?
hei bro, yes i want share my solution for this error.

1. you must go to your project > node_modules/react-native-voice/android/src/main/java/com/wenkesj/voice
2. find VoiceModule.java
3. and replace function startSpeech with this code

`  @ReactMethod
  public void startSpeech(final String locale, final ReadableMap opts, final Callback callback) {

    this.locale = locale;

    Handler mainHandler = new Handler(this.reactContext.getMainLooper());
    mainHandler.post(new Runnable() {
      @Override
      public void run() {
        try {
          startListening(opts);
          isRecognizing = true;
          callback.invoke(false);
        } catch (Exception e) {
          callback.invoke(e.getMessage());
        }
      }
    });
  }`

4. and done, lets try your project with npm start > react-native run-android
5. congrats

**Comment by sibelius** [comment]
I think this is solved on latest release

check here

https://github.com/wenkesj/react-native-voice/blob/master/android/src/main/java/com/wenkesj/voice/VoiceModule.java#L138-L152

**Comment by darknblack** [comment]
Not working to me :(
