### ISSUE TITLE
Native voice!react native

### ISSUE THREAD

**Issue by EmiMiron** [wenkesj/react-native-voice#131]
Hy guys.i have 1 problem .i want to use the native voice plugin and doesn;t work.my error is : 

[TypeError: undefined is not an object (evaluating 'Voice.startSpeech')] 

 i respect every step and i install everything,i put react-native link,i uncommented the import from android,i do everything from the internet.i made a project with react init and other with create react native and i have the same error.Can someone help me plz?

**Comment by KarenMosavat** [comment]
HI, I made a project for both android and IOS recently and I dont have any problem with that, I suggest you to download voice test project from react-native-voice and make your project like that.
