### ISSUE TITLE
IOS crash when use Voice.start('en-US').

### ISSUE THREAD

**Issue by pekubu** [wenkesj/react-native-voice#136]
It works fine on android, but on IOS it crashed when I used the function Voice.start('en-US').
Has anyone encountered this problem yet? I can't find log error, plz help me
XCode 10.
IOS 12.
React native: 0.57.3

**Comment by gglee89** [comment]
@pekubu Mine doesn't crash but on iOS, after the function `Voice.start('en-US')` is invoked the sound from the `case speakers` gets shifted to the `ear speakers`.

```
XCode 10
iOS 12.0.1
react-native: 0.57.2
react-native-tts: "^2.0.0"
react-native-voice: "^0.2.6"
```

In your case, it could be maybe related with your app's permission to access the `SpeechRecognition`.

Check if you have the entry:
`Privacy - Speech Recognition Usage Description`

**Comment by sibelius** [comment]
try to use master instead

**Comment by pekubu** [comment]
@gglee89 @sibelius  Thank you so much.
I used master, It working.
But sometimes it still crashed (When the recognizer finishes)

**Comment by tahir-jamil** [comment]
not working for me 
this is package.json i am using 

>     "react-native-voice": "git+https://github.com/wenkesj/react-native-voice.git#master",
this is how i init the plugin
```
  try {
            await Voice.start('en-US');
        } catch (e) {
            //eslint-disable-next-line
            console.error(e);
        }
```

**Comment by pekubu** [comment]
@tahir-jamil 
Are there any specific errors?

**Comment by subhendukundu** [comment]
Looks like it's happening only with latest react-native versions.
I tried upgrading my app from `"react-native": "0.59.9"` to `"react-native": "0.61.1"` crashing the app.
Works great with `"react-native": "0.59.9"`.

**Comment by sanjaymachetti** [comment]
add below code to ios/app_name/Info.plist file in RN(React Native) project folder to set the permission on iOS.
This did the trick for me.

[https://dev-yakuza.github.io/en/react-native/react-native-voice/](url)
`
<dict>
    ...
    <key>NSMicrophoneUsageDescription</key>
    <string>Description of why you require the use of the microphone</string>
    <key>NSSpeechRecognitionUsageDescription</key>
    <string>Description of why you require the use of the speech recognition</string>
    ...
</dict>
`

**Comment by gdm-1718-jantemme** [comment]
Has there been any updates on this? i'm on "react-native": "^0.62.2"

**Comment by ishanm** [comment]
I'd love to know if there have been any updates as well 🙏

**Comment by adamgusky** [comment]
Still no updates for the latest react version?
