### ISSUE TITLE
Running with ejected expo app

### ISSUE THREAD

**Issue by ersel** [wenkesj/react-native-voice#137]
Trying to run this library on an ejected expo app. I have installed the dependency, linked and rebuilt.

I am trying to run the example found in the docs, but when I click the button which calls `await Voice.start('en-US');` App fails with the following error message:

```
host.exp.exponent.MainActivity cannot be cast to com.facebook.react.ReactActivity
startSpeech
    VoiceModule.java:121
invoke
    Method.java
invoke
    JavaMethodWrapper.java:372
invoke
    JavaModuleWrapper.java:160
run
    NativeRunnable.java
handleCallback
    Handler.java:873
dispatchMessage
    Handler.java:99
dispatchMessage
    MessageQueueThreadHandler.java:29
loop
    Looper.java:193
run
    MessageQueueThreadImpl.java:192
run
    Thread.java:764
```

Any ideas, where I should be looking at? It looks like there is a mismatch between activity type expected.

**Comment by maxmatthews** [comment]
I ran into the same issue and solved it by asking for audio recording permissions using `expo-permissions` before starting voice recognition. 
```js
import { Permissions } from "expo";
async componentDidMount() {
	const { status, expires, permissions } = await Permissions.askAsync(
		Permissions.AUDIO_RECORDING
	);
	if (status !== "granted") {
		alert("Permissions not granted. Don't show the start recording button because it will cause problems if it's pressed.");
		this.setState({showRecordButton: false});
	}
}
```

**Comment by sibelius** [comment]
@maxmathews can you add this to the docs?

**Comment by maxmatthews** [comment]
Sure. Done in: https://github.com/wenkesj/react-native-voice/pull/140

**Comment by sibelius** [comment]
tks
