### ISSUE TITLE
Enabling word-level confidence in a request

### ISSUE THREAD

**Issue by afacar** [wenkesj/react-native-voice#143]
I need the confidence scores for the results returned.  On google speech api (https://cloud.google.com/speech-to-text/docs/word-confidence#speech-word-level-confidence-nodejs) I found such a config parameter:
```
const config = {
  encoding: `FLAC`,
  sampleRateHertz: 16000,
  languageCode: `en-US`,
  enableWordConfidence: true,
};
```
Is there a way to do this in this library? 
Thanks in advance

**Comment by ohtangza** [comment]
That is for a paid API. With the default SDK this library relies on, we cannot extract that info.

**Comment by tslater** [comment]
Don't the native libraries provide confidence as well? I am looking here at the docs. Would it be possible to surface this information? Would you accept a PR?

https://developer.apple.com/documentation/speech
