### ISSUE TITLE
Possibility of the Library to implement Speech to text Offline? 

### ISSUE THREAD

**Issue by tejparekh** [wenkesj/react-native-voice#145]
I am planning to implement the form which will have input from the user as a voice commands. 
For. e.g. The user will speak the options shown on screen. "Yes", "No" or "Not Applicable"
I need the user to speak the option and based on that the answer will be selected in the form. 
NOTE - I need that Speect - to - Text translation to happend offline. Is this something possible with this Library react-native-voice? or If you can direct me to the right library that will be great. 
This is required on a new project hence the configurations can be set as per the capability of the libraruy. 

Any suggestions and inputs are much appreciated. 
Thanks!

**Comment by ohtangza** [comment]
I think the offline support is beyond the scope of this repository because it uses the cloud-based ASR behind the scene. I think if you want those features, you need to try like https://cmusphinx.github.io/wiki/tutorialandroid/

**Comment by jshin49** [comment]
@ohtangza May I ask which cloud-based ASR API is used behind the scenes?
