### ISSUE TITLE
Conflict between react-native-voice and text-to-speech

### ISSUE THREAD

**Issue by under94** [wenkesj/react-native-voice#146]
Look [here](https://github.com/ak1394/react-native-tts/issues/104)

**Comment by sibelius** [comment]
have you tried master?

**Comment by under94** [comment]
@sibelius yep! It doesn’t works. If you want, you can try with my code

**Comment by sibelius** [comment]
Can you post the stack trace?

**Comment by under94** [comment]
Solved

**Comment by sibelius** [comment]
@under94 how?

**Comment by under94** [comment]
You have to edit Voice.m adding the right category of AVAudioSession:

- Inside `startSpeech` you have to add (as first line):   `[[AVAudioSession sharedInstance] setCategory:AVAudioSessionCategoryPlayAndRecord error:nil];`

- Now, inside `destroySpeech`: `[[AVAudioSession sharedInstance] setCategory:AVAudioSessionCategoryAmbient error:nil];`  So, after speech-to-text you have to call the destroy method, then you can play a sound with react-native-tts.

I don't know if this is the right solution, but for me, it works.

**Comment by AlexM2807** [comment]
@under94  its work, thank you !
