### ISSUE TITLE
integration with Dialogflow

### ISSUE THREAD

**Issue by lfoliveir4** [wenkesj/react-native-voice#178]
I am trying to use react native voice to perform integration with the dialogflow API.
When I press the button to speak it appears the error below:

![image](https://user-images.githubusercontent.com/32423942/57173068-d1798180-6dff-11e9-839a-721609311285.png)

Script:

import React, { Component } from 'react';
import { StyleSheet, Text, Button,  View, Image,  TouchableOpacity, ToastAndroid } from 'react-native';

import Voice from 'react-native-voice'
import Tts from 'react-native-tts'
import { TOKEN_CHAT } from '../constants/accessToken'

export default class ChatbotPage extends Component {
  constructor(props) {
    super(props);
    this.onSpeak = this.onSpeak.bind(this);
    this.getDialogFlow = this.getDialogFlow.bind(this);
    this.state = { showText: "" };
  }

  async getDialogFlow(msg) {

    try {
       const response = await fetch(`https://api.dialogflow.com/v1/query?v=20170712`, {
        method: 'POST',
        headers: {
          'Accept': 'application/json',
          'Content-Type': 'application/json; charset=utf-8',
          'Authorization': `Bearer ${TOKEN_CHAT}`,
        },
        body: JSON.stringify({
          query: msg,
          lang: 'PT-BR',
          sessionId: 'somerandomthing'
        })
      })

      let responseJson = await response.json();

      this.setState({
        showText: responseJson.result.fulfillment.speech,
      });
      
      return responseJson;

    } catch(error) {
      console.error(error);
    }
  }

  async onSpeak() {
    try {
      const spokenText = await Voice.start("pt-BR");

      const dialogflowResponse = await this.getDialogFlow(spokenText);
      if (this.state.showText) {
        Tts.setDefaultLanguage("pt-BR")
        Tts.speak(dialogflowResponse.result.fulfillment.speech);
        ToastAndroid.show(dialogflowResponse.result.fulfillment.speech, ToastAndroid.LONG);
      }
    } catch(error) {
      console.log("error")
    }
  }

  render() {
    return (
      <View style={styles.container}>

      <Text style={styles.textBot}>Aperte o logo e diga Olá para começar! </Text>
      <TouchableOpacity
      onPress={this.onSpeak}
      >
      <Image
      source={ require('../img/logo.png') }
      />
      </TouchableOpacity>

      </View>
    );
  }
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#F5FCFF',
  },

  textBot: {
    marginBottom: 40,
  }
});

Versions:
"react-native": "0.59.5",

**Comment by sibelius** [comment]
This is not a problem with react native voice

The response can be null
