### ISSUE TITLE
Continuously listening to user input

### ISSUE THREAD

**Issue by henrych4** [wenkesj/react-native-voice#20]
It seems that the voice detecting function will terminate after starting detection a few seconds. Is there exist a way to keep listening to user input?

Thanks!

**Comment by dgurns** [comment]
Would love to know this as well.

**Comment by wenkesj** [comment]
This has been a suggestion in the past, so I started implementing this with `Android` (first). In `0.2.x` you now have (limited) access to the RecognizerIntent `EXTRA_*` options such as `EXTRA_SPEECH_INPUT_MINIMUM_LENGTH_MILLIS` 
`EXTRA_SPEECH_INPUT_COMPLETE_SILENCE_LENGTH_MILLIS` 
`EXTRA_SPEECH_INPUT_POSSIBLY_COMPLETE_SILENCE_LENGTH_MILLIS` are now customizable.

**For example**, to force the intent to recognize for 10 seconds without stopping,
```js
Voice.start('en-US', {
  EXTRA_SPEECH_INPUT_MINIMUM_LENGTH_MILLIS: 10000
});
```

**Comment by dgurns** [comment]
Awesome news! I had played around with setting these as hardcoded values in the component java files, but they didn't seem to have any effect. Have you been able to get them working?

**Comment by AidanDaniel97** [comment]
This isn't working for me on android - is there an alternative to getting this running continuously? or at least increasing the time for silence?

**Comment by ZhiSh3n** [comment]
Editing the hardcoded values in the java files don't work for me either.

**Comment by darknblack** [comment]
not working to me as well :(

**Comment by FabioSchmidberger** [comment]
Hi, are there any updates on this issue? We have the same problem using target api 28. Would be happy to contribute to a fix of this issue.

**Comment by sjc5** [comment]
Any updates on this? It is not working for me either.
