### ISSUE TITLE
Voice.Stop is not working.

### ISSUE THREAD

**Issue by ozsirma** [wenkesj/react-native-voice#22]
I start speech.It is working voice.start() but stop is not working.

**Comment by dgurns** [comment]
I'm having the same issue -- neither Voice.stop() or Voice.destroy() are working. Both produce this error: 

![simulator screen shot aug 22 2017 11 36 50 am](https://user-images.githubusercontent.com/1173791/29574143-b84b4392-872e-11e7-9120-86afe1faf9d8.png)

**Comment by ohtangza** [comment]
I am experiencing this in RN0.44 too. Any clue?

**Comment by ohtangza** [comment]
I spent 8 hours for trying to fix it but had no luck. If anyone knows what this error's about. Please let me know :(

**Comment by ohtangza** [comment]
I finally ended up finding a solution. The error disappeared after I upgraded RN version from 0.44.0 to 0.46.4.
