### ISSUE TITLE
Does this convert speech to text in real-time?

### ISSUE THREAD

**Issue by anchetaWern** [wenkesj/react-native-voice#23]
Hello! Does this library recognize speech and converts it to text in real-time? I mean when I say "one" and then pause for 1 second and then say "two". Will those two words trigger two separate callbacks? 

There are at least 2 events that potentially does what I want to accomplish:

- onSpeechRecognized
- onSpeechPartialResults

Which one of these gets executed every time a single word is recognized? Thanks!

**Comment by noelweichbrodt** [comment]
@anchetaWern this library performs real-time speech recognition. Silence triggering two different callbacks is configured on a per-os (eg android or ios) ASR basis. 

An example would probably clear this up for you. Here is logging output from a continuous utterance with small pauses (> 1s). I've hooked up the relevant callbacks and run in iOS.

```
started
index.ios.bundle:1323 results: Be
index.ios.bundle:1331 partial results: Be
index.ios.bundle:1299 recognized
index.ios.bundle:1323 results: Do
index.ios.bundle:1331 partial results: Do
index.ios.bundle:1299 recognized
index.ios.bundle:1323 results: Do you
index.ios.bundle:1331 partial results: Do you
index.ios.bundle:1299 recognized
index.ios.bundle:1323 results: Do you were
index.ios.bundle:1331 partial results: Do you were
index.ios.bundle:1299 recognized
index.ios.bundle:1323 results: Do you were only
index.ios.bundle:1331 partial results: Do you were only
index.ios.bundle:1299 recognized
index.ios.bundle:1323 results: Do you were only sleeping
index.ios.bundle:1331 partial results: Do you were only sleeping
index.ios.bundle:1299 recognized
index.ios.bundle:1323 results: Do you were only sleeping
index.ios.bundle:1331 partial results: Do you were only sleeping
index.ios.bundle:1299 recognized
```

**Comment by rubencg195** [comment]
Is there a way to speed up the partial result output stream since I've seen that in Android the recognition is very slow. The example has been tested in both Note 3 and Galaxy S5, Wifi connection to ensure a stable server connection.

**Comment by ohtangza** [comment]
@rubencg195 Since Android's ASR relies on Google's server, the latency is highly dependent on the network time between user and Google. Try to run `ping cloudspeech.goog` on your terminal and compare mine (in Seoul, Korea) with yours. it will be really appreciated if you share your location and the round-trip time, in my case 189ms.

<img width="479" alt="screen shot 2018-01-03 at 11 48 21 pm" src="https://user-images.githubusercontent.com/1323963/34524947-ac3c9238-f0e0-11e7-9aa9-a6791b39d244.png">

**Comment by rubencg195** [comment]
![image](https://user-images.githubusercontent.com/25628940/34526286-f948fa04-f099-11e7-851e-d84cf8065f83.png)
 
This is my results, around 162 ms and my location is London, UK. Still is weird, it takes up to 2-3 seconds to start producing a result in the event callback, If there is any filter or process before the callback that can be slowing down the callback and can be taken out, I will appreciate the help.

**Comment by ohtangza** [comment]
@rubencg195 Perhaps, Google only returns when they are 100% sure about their result (without interim recognition).

**Comment by sibelius** [comment]
this is a bridge for both ios and android native libraries, if it is not so fast, it is hard to us to solve this
