### ISSUE TITLE
Show Android speech interface?

### ISSUE THREAD

**Issue by dgurns** [wenkesj/react-native-voice#24]
When using this component for Android, is there any way to show the native Android speech recognizer interface? 

![qaftd](https://user-images.githubusercontent.com/1173791/30073223-132e086e-923b-11e7-8aab-f5bdbe05caa5.png)

**Comment by wenkesj** [comment]
@dgurns There actually is a way, but to ensure all platforms are isomorphic I decided to opt out of UI tools for this library. Although, from `0.2.0` on, I am starting to grant access to [RecognizerIntent ](https://developer.android.com/reference/android/speech/RecognizerIntent.html) options, available through the `Voice.start(locale, options = {...})`. This would be where you may possibly incorporate something like this. I would suggest implementing that through the native code (although I'm not positive what the API is, but that link may help).
