### ISSUE TITLE
offline use

### ISSUE THREAD

**Issue by fenicento** [wenkesj/react-native-voice#27]
Hi, would it be possible to provide text-to-speech while offline, at least for android? I'm not a native developer, but this:

https://developer.android.com/reference/android/speech/RecognizerIntent.html#EXTRA_PREFER_OFFLINE

should do the trick, right?

**Comment by mattbreeden** [comment]
It will do this by default (users may have had to enable a setting somewhere). Setting that flag forces it to always use offline even if there is a connection.

**Comment by wenkesj** [comment]
Closing because @mattbreeden, [docs says] (https://developer.android.com/reference/android/speech/RecognizerIntent.html#EXTRA_PREFER_OFFLINE) quote from page

> "...to indicate whether to only use an offline speech recognition engine. The default is false, meaning that either network or offline recognition engines may be used."
