### ISSUE TITLE
iOS only saves the first word of the phrase

### ISSUE THREAD

**Issue by travisday** [wenkesj/react-native-voice#30]
Anyone know why it would only capture the first word? It is working fine on Android this issue is only occurring on iOS. I am not sure if it is only returning the first word, or is stopping listening after the first word is recognized.

**Comment by wenkesj** [comment]
Let me know if this is still an issue in release [0.2.0](https://github.com/wenkesj/react-native-voice/releases/tag/v0.2.0)

**Comment by mjhassan** [comment]
@wenkesj, the issue still exist in 0.2.6#master.
