### ISSUE TITLE
Not recognize for iOS

### ISSUE THREAD

**Issue by tungcsc103** [wenkesj/react-native-voice#31]
This lib works well in Android.
As my debug, Voice.onSpeechStart(event) is triggered but Voice.onSpeechRecognized(event) is not called.

I'm using:
react-native-voice: 0.1.12
react: 16.0.0-alpha.12
react-native: 0.46.4

Regards!

**Comment by wenkesj** [comment]
@tungcsc103 I have fixed this in 0.2.0, please give this a try
