### ISSUE TITLE
Voice.stop() doesn't work as expected

### ISSUE THREAD

**Issue by alexeymolchan** [wenkesj/react-native-voice#32]
IOS,
react-native: 0.48.2,
react-native-voice: 0.2.1,

Hi

So basically when i try to call Voice.stop() without any recognized voice i receive Error (203/Retry).

But if i have at least 1 recognized word Voice.stop() works fine

**Comment by maurovisintin** [comment]
@alexeymolchan did you solve this?

**Comment by alexeymolchan** [comment]
@maurovisintin if I'm not mistaken, i caught this error and then called Voice.destroy(), but im not sure. Unfortunately i don't have source code of the project in which i used react-native-voice :(

**Comment by maurovisintin** [comment]
@alexeymolchan i tried to Voice.destroy() inside the catch, but with no luck  :(

**Comment by alexeymolchan** [comment]
@maurovisintin have you tried in this callback Voice.onSpeechError(event) ?

**Comment by maurovisintin** [comment]
@alexeymolchan yep i tried! no luck there either
