### ISSUE TITLE
[TypeError: undefined is not an object (evaluating 'Voice.startSpeech')]

### ISSUE THREAD

**Issue by tuannguyennv** [wenkesj/react-native-voice#36]
when i install this package and a call on button press:  await Voice.start("en-US");

Genymotion cause this error

Any helps.

**Comment by EroticCode** [comment]
same isssue

**Comment by hudsonmendes** [comment]
same issue, on an android device, 'pt-BR'

**Comment by rubencg195** [comment]
same issue

**Comment by martijndeh** [comment]
Can you confirm you executed `react-native link` after installing?

**Comment by anaerobic** [comment]
hello! try these steps:
```
# uninstall app
# stop packager
watchman watch-del-all
rm -rf $TMPDIR/react-*
rm -rf $TMPDIR/haste-*
rm -rf $TMPDIR/metro-*
# restart packager
# run android
```

**Comment by jonnycraze** [comment]
Is it possible to confirm if I've linked it correctly after installing?

I'm having the same problem, and I'm suspicious of the link.

**Comment by nicmitchell** [comment]
I had the same problem. In my case, `react-native link` wasn't working.

After following the documentation for linking manually, I noticed this in `MainApplication.java`:
```
// Needed for `react-native link`
// import com.facebook.react.ReactApplication;
...
```
I uncommented that `import` statement and ran the `react-native link react-native-voice` command again. That solved the problem for me.

**Comment by EmiMiron** [comment]
Guys ,plz help.i have the same problem.what can i do ? i respect every step and i install everything,i put react-native link,i uncommented the import from android,i do everything from the internet.i made a project with react init and other with create react native and i have the same error.Can someone help me plz?

**Comment by sibelius** [comment]
check example

this only happens when `Voice` is undefined, so the link is wrong

relink and rebuild

**Comment by lfoliveir4** [comment]
![image](https://user-images.githubusercontent.com/32423942/56103725-a55a9700-5f0a-11e9-8722-bfb0a6abf2c9.png)

this error

**Comment by AlcuinGuest** [comment]
For anyone coming across this again, on top of linking (which didn't work even though it says it did), I had to follow the manual linking steps. This issue then went away and it works great!

**Comment by swapnilisrael** [comment]
@lfoliveir4 can you please provide me the link for manual linking steps

**Comment by swapnilisrael** [comment]
@24dev can you please provide me the link for manual linking steps

**Comment by 24dev** [comment]
@swapnilisrael https://github.com/react-native-community/voice#manually-link-android

**Comment by abhineetsharmathegreat** [comment]
Hey having the same problem. Any suggestions because I am using this on Expo and it does not work.

**Comment by abhineetsharmathegreat** [comment]
Hey having the same problem. Any suggestions because I am using this on Expo and it does not work.

**Comment by code123841** [comment]
hey @24dev  Im Using Expo Too having the same Problem Any Suggestions?

**Comment by svanin91** [comment]
hi guys, has anyone solved the problem?
