### ISSUE TITLE
Minimum Android version?

### ISSUE THREAD

**Issue by Noitidart** [wenkesj/react-native-voice#38]
Hi there, thanks for this awesome lib. What is the minimum android version? RN supports down to 4.1.

**Comment by ohtangza** [comment]
According to the following information, the speech recognition should be supported by Android 2.2 or higher.

- https://developer.android.com/reference/android/speech/SpeechRecognizer.html
- https://developer.android.com/about/versions/android-2.2.html

So, minimum version should be 4.1 as you mentioned.

**Comment by Noitidart** [comment]
Thank you @ohtangza !
