### ISSUE TITLE
Offline Speech Recognition

### ISSUE THREAD

**Issue by aamping** [wenkesj/react-native-voice#45]
Hi,
I read that this react-native-voice provides Online and Offline Support.

Does this mean that it can work offline?

I tested it and it keeps popping network error when I try offline on my AVD.

Any thoughts?

Thanks

**Comment by AriaEdo** [comment]
Just download `Offline speech recognition` in settings > language and input > Voice input (this can be difference on every device).
Then add EXTRA_PREFER_OFFLINE intent.

**Comment by Noitidart** [comment]
Thanks for this question and explanation it wasn't clear. Maybe we should mention this in the docs somewhere.

We have to tell our users to download the "offlice speech recognition" correct? Both ios and android?

And for android only we need ot add EXTRA_PREFER_OFFLINE permission?

**Comment by aamping** [comment]
Should the EXTRA_PREFER_OFFLINE intent be added during startSpeech as an option?

**Comment by sibelius** [comment]
it does work offline and online

use EXTRA_PREFER_OFFLINE on android, check docs

**Comment by Ash-faq** [comment]
Where is the details about EXTRA_PREFER_OFFLINE is available in the docs @sibelius

**Comment by Ash-faq** [comment]
iam not getting the exact text what i speak but its working fine in online @sibelius
