### ISSUE TITLE
Play Sound

### ISSUE THREAD

**Issue by ardboer** [wenkesj/react-native-voice#49]
Awesome module! Is it possible to play a sound or speak text? If I use this module together with react-native-audio-toolkit it crashes(iOS) when I want to play a sound in my App.

**Comment by Noitidart** [comment]
That is not the purpose of this module. To play sounds you should use react-native-sound - https://github.com/zmxv/react-native-sound - which is a very mature project.

To convert text to speech there is another popular package out there, I can't recall it but it's pretty well supported.

**Comment by Noitidart** [comment]
@ardboer found the speech lib - react-native-speech - https://github.com/naoufal/react-native-speech - very good package.

**Comment by ohtangza** [comment]
`react-native-speech` should be a good choice. I'm closing this issue now.
