### ISSUE TITLE
Library not loaded: /System/Library/Frameworks/Speech.framework/Speech

### ISSUE THREAD

**Issue by abaddonGIT** [wenkesj/react-native-voice#55]
Guys please help after install not open project in emulator and real device(
Library not loaded: /System/Library/Frameworks/Speech.framework/Speech

**Comment by ohtangza** [comment]
Too little info to answer, I think.

**Comment by abaddonGIT** [comment]
![1](https://user-images.githubusercontent.com/3716060/34617810-a40fbc84-f24d-11e7-8e0a-269968994376.png)
![2](https://user-images.githubusercontent.com/3716060/34617829-b6abc3f6-f24d-11e7-96e3-efb82a7430db.png)
![3](https://user-images.githubusercontent.com/3716060/34617852-c30bfefe-f24d-11e7-94df-5c0802617a7a.png)

**Comment by abaddonGIT** [comment]
What more information else is needed?

**Comment by abaddonGIT** [comment]
![4](https://user-images.githubusercontent.com/3716060/34618194-0793e2ca-f24f-11e7-94ff-9368807abdd1.png)

**Comment by abaddonGIT** [comment]
This error only ios version < 10. If you want start app on ios < 10 you should set "Optional" for libVoice.a and Speech.framework in "Linked Frameworks and Libraries"
