### ISSUE TITLE
Cannot read property 'startSpeech' of undefined

### ISSUE THREAD

**Issue by dohvis** [wenkesj/react-native-voice#57]
Voice is undefined 
https://github.com/wenkesj/react-native-voice/blob/master/index.js#L8

**Comment by anaerobic** [comment]
hello! try these steps:
```
# uninstall app
stop packager
watchman watch-del-all
rm -rf $TMPDIR/react-*
rm -rf $TMPDIR/haste-*
rm -rf $TMPDIR/metro-*
# restart packager
# run android
```

**Comment by jonnycraze** [comment]
@anaerobic 

Is it possible to confirm if I've linked it correctly after installing?
I'm having the same problem, and I'm suspicious of the link.

**Comment by jonnycraze** [comment]
However my error is 
```typeerror: undefined is not an object (evaluating 'Voice.onSpeechResults ... ```

**Comment by jonnycraze** [comment]
If you built your app using:  create-react-native-app it cannot use native components like this.

aka ```react-natve link``` won't work

Instead use react-native init

**Comment by sun2rise** [comment]
tragedy :/

**Comment by sibelius** [comment]
`react-native link react-native-voice`

rebuild

**Comment by lfoliveir4** [comment]
![image](https://user-images.githubusercontent.com/32423942/56103793-f9657b80-5f0a-11e9-8a37-70f428b86b4f.png)


this error on SpeehRecognition

**Comment by Kiruba-sagar** [comment]
error while recording [TypeError: Cannot read property 'startSpeech' of null]

**Comment by ahadnawaz585** [comment]
> ![image](https://user-images.githubusercontent.com/32423942/56103793-f9657b80-5f0a-11e9-8a37-70f428b86b4f.png)
> 
> this error on SpeehRecognition

Hey ! have you solved it ? i am still stucked in it and now it's making me feel exhausted!
