### ISSUE TITLE
example from project is not working

### ISSUE THREAD

**Issue by sumanbogati** [wenkesj/react-native-voice#6]
I have tried to run your example from this project but it does not work. It shows below error.

![image](https://cloud.githubusercontent.com/assets/1753974/23338850/2d3737bc-fc3b-11e6-9ec4-709a8beaa062.png)

What I have done wrong, can you please give some light on this?

**Comment by wenkesj** [comment]
This seems like a problem with Gradle and your setup. Try to follow [Android Setup](https://facebook.github.io/react-native/releases/0.23/docs/android-setup.html) and see if that works. Closing this as question
