### ISSUE TITLE
Can you use it with other language than English?

### ISSUE THREAD

**Issue by CFarcy** [wenkesj/react-native-voice#62]
Hello, I tried to use react-native-voice and it works perfectly. But now I would like to use it with french. I replace en-US with fr-FR in Voice.start('en-US') but it doesn't works at all (except if I speak english).

**Comment by CFarcy** [comment]
Yes it is. I updated my nodejs version and it works properly now. Thanks a lot for you quick answer 👍

**Comment by ohtangza** [comment]
@CFarcy Cheers!
