### ISSUE TITLE
support ios 9.x ?

### ISSUE THREAD

**Issue by blackstar217** [wenkesj/react-native-voice#68]
I have built an app with Xcode9.2(ios version 11.2). It works on ios version11.x, but it doesn't work on ios version 9.x
when I run on ios 9.x, the app crashed. 
error: 
dyld: Library not loaded: /System/Library/Frameworks/Speech.framework/Speech 

and I got the error when I run the app on android like this
Service not registered: android.speech.SpeechRecognizer

I followed your doc exactly. but I got the above error.

**Comment by ohtangza** [comment]
Apple supports speech recognition since iOS 10+ (https://developer.apple.com/documentation/speech). This is not the matter of this library.
