### ISSUE TITLE
'React/RCTBridgeModule.h' file not found

### ISSUE THREAD

**Issue by alvaro1728** [wenkesj/react-native-voice#69]
Hi,

I just added this to what used to be an attached Expo project.  These were my command-line steps:

1. exp detach
2. npm i react-native-cli -g
3. sudo gem install cocoapods
4. cd ios
5. pod install
6. cd ..
7. **npm i react-native-voice -S**
8. **react-native link react-native-voice**

I then opened my project's xcworkspace in Xcode and clicked the Build button.  I'm getting one error, in file Voice.h:

**'React/RCTBridgeModule.h' file not found**

I went looking for this file and I see that it's in my ios/Pods/Headers/Private/React/React directory.  So what's going on?  Please help!

Thanks,
Alvaro

**Comment by alvaro1728** [comment]
Inside Xcode, I clicked on the Voice.xcodeproj file under Libraries and added this to Build Settings/Search Paths/Header Search Paths:  **$(SRCROOT)/../../../ios/Pods/Headers/Private/React**.  That got rid of the error but I'm not sure it's the proper solution.

**Comment by sibelius** [comment]
I think this is a problem only when using cocoapods
