### ISSUE TITLE
How can i use recognition and recording at the same time

### ISSUE THREAD

**Issue by anhntbk08** [wenkesj/react-native-voice#77]
Hi,

First of all, thanks for great library.

Can you help me out how to recognition and record at the same time? I tried out using this library for recognition and react-native-audio for recording but got conflicting audio resource issue.

Thank for your time.

**Comment by ohtangza** [comment]
I am sorry to say that it's not feasible with this library.

In Android, you can't. Google used to support it, but recently, does not fire the buffer callback for recent version of Android.

In iOS, it's possible, but you should provide the raw buffer using AvAudioEngine, which is beyond the role of this library. This library currently serves as a wrapper for the official SpeechRecognition library.

**Comment by anhntbk08** [comment]
Thanks @ohtangza  for your quick support.

Let me close this.

**Comment by Hirurgo** [comment]
@anhntbk08 take a look on this issue https://github.com/react-native-voice/voice/issues/185
