### ISSUE TITLE
Is this implemented anywhere? `onSpeechVolumeChanged`

### ISSUE THREAD

**Issue by iMagdy** [wenkesj/react-native-voice#78]
https://github.com/wenkesj/react-native-voice/blob/99a2c84725a308274a87c87f336eef1d6cf7e637/ios/Voice/Voice.m#L120

**Comment by karthikmuralidharan** [comment]
On the Readme, it specifically mentions Android only. You seem to be looking for it in iOS.

**Comment by iMagdy** [comment]
Oh sorry, my bad! I didn't notice it was Android only.
