### ISSUE TITLE
FAILURE: Build failed with an exception.

### ISSUE THREAD

**Issue by GuillaumeJulien** [wenkesj/react-native-voice#8]
Hi,
I tried to install this package but something wrong append when I build :  
I've link the package with :
`react-native link react-native-voice`
and i've update the gradle settings & the gardle build correctly 

and this build return :   
```
Execution failed for task ':app:processDebugResources'.
> Error: more than one library with package name 'com.wenkesj.voice'
```

What should i do to fix that ? 
Tanks

**Comment by prajkay** [comment]
Hey man, just make sure you remove this line 
`compile project(':VoiceModule')`
from your `android/app/build.gradle`

**Comment by wenkesj** [comment]
Closing this in favor of the above comment, @pkandarpa-cs thanks
