### ISSUE TITLE
List of locale available

### ISSUE THREAD

**Issue by MrHazimAli** [wenkesj/react-native-voice#83]
Hye, I would like to know where can I check locale supported for this package? Im looking for arabic locale code.

**Comment by Noitidart** [comment]
There is an open issue for this - https://github.com/wenkesj/react-native-voice/issues/54

Side note, I am also looking for Arabic. I didn't know that was supported!

**Comment by Noitidart** [comment]
My guess would be it is either:

Because here - https://developer.apple.com/library/content/documentation/MacOSX/Conceptual/BPInternational/LanguageandLocaleIDs/LanguageandLocaleIDs.html - it links to http://www.loc.gov/standards/iso639-2/php/English_list.php

Which has - `ara` or `ar`

**Comment by MrHazimAli** [comment]
Im guess is this.. from google, but can't find arabic

https://developers.google.com/actions/localization/languages-locales

**Comment by jamsch** [comment]
Here's a few. The values are the locales for the respective platforms
```javascript
const iosLocales = {
  'ar-EG': 'ar_EG',
  'de-DE': 'de_DE',
  'en-US': 'en_US',
  'es-CL': 'es_CL',
  'fr-FR': 'fr_FR',
  hi: 'hi_IN',
  'it-IT': 'it_IT',
  ja: 'ja_JP',
  ko: 'ko_KR',
  'pt-BR': 'pt_BR',
  ru: 'ru_RU',
  'zh-CN': 'zh_Hans_SG',
};

const androidLocales = {
  'ar-EG': 'ar-EG',
  'de-DE': 'de-DE',
  'en-US': 'en_US',
  'es-CL': 'es-CL',
  'fr-FR': 'fr-FR',
  hi: 'hi-IN',
  'it-IT': 'it-IT',
  ja: 'ja-JP',
  ko: 'ko-KR',
  'pt-BR': 'pt-BR',
  ru: 'ru-RU',
  'zh-CN': 'cmn-Hans-CN',
};
```

**Comment by Noitidart** [comment]
Thank you so much @jamsch that's a super help! Where did you find those?

@MrHazimAli it seems there is ar-egyption in ios and android too.

**Comment by MrHazimAli** [comment]
thanks @jamsch ! 
yup.. that's nice @Noitidart 💯

**Comment by ohtangza** [comment]
I think this feature saves lots of confusion and time of devs.

**Comment by tejachundru** [comment]
Here These are total supported locale with codes for iOS as of now for speech Recognition

For iOS Only,
          Nederland : nl-NL
          México : es-MX
          台灣 : zh-TW
          France : fr-FR
          Italia : it-IT
          Việt Nam : vi-VN
          Suisse : fr-CH
          South Africa : en-ZA
          Espanya : ca-ES
          대한민국 : ko-KR
          Chile : es-CL
          România : ro-RO
          Philippines : en-PH
          Latinoamérica : es-      
          Canada : en-CA
          Singapore : en-SG
          India : en-IN
          New Zealand : en-NZ
          Svizzera : it-CH
          Canada : fr-CA
          भारत : hi-IN
          Danmark : da-DK
          Österreich : de-AT
          Brasil : pt-BR
          中华人民共和国 : yue-CN
          中国 : zh-CN
          Sverige : sv-SE
          भारत : hi-IN-translit
          España : es-ES
          Magyarország : hu-HU
          المملكة العربية السعودية : ar-SA
          Belgique : fr-BE
          United Kingdom : en-GB
          日本 : ja-JP
          香港（中國） : zh-HK
          Suomi : fi-FI
          Türkiye : tr-TR
          Norge : nb-NO
          Indonesia : en-ID
          Saudi Arabia : en-SA
          Polska : pl-PL
          Indonesia : id-ID
          Malaysia : ms-MY
          Ελλάδα : el-GR
          Česko : cs-CZ
          Hrvatska : hr-HR
          United Arab Emirates : en-AE
          ישראל : he-IL
          Россия : ru-RU
          China : wuu-CN
          Schweiz : de-CH
          Australia : en-AU
          Deutschland : de-DE
          België : nl-BE
          ไทย : th-TH
          Portugal : pt-PT
          Slovensko : sk-SK
          United States : en-US
          Ireland : en-IE
          Colombia : es-CO
          (null) : hi-Latn
          Україна : uk-UA
          Estados Unidos : es-US

Someone Could Update Android too.

**Comment by sibelius** [comment]
send PR please

**Comment by ducpt2** [comment]
Is there any way to check if the language is possible to regconition please? Thanks.

**Comment by mongfaay** [comment]
Any React Native Developer who is looking for opportunities?

**Comment by gks-96** [comment]
I'm trying to find support for Punjabi language,is there any way i can find whether react-native-voice supports it or not?   

> Here These are total supported locale with codes for iOS as of now for speech Recognition
> 
> For iOS Only, Nederland : nl-NL México : es-MX 台灣 : zh-TW France : fr-FR Italia : it-IT Việt Nam : vi-VN Suisse : fr-CH South Africa : en-ZA Espanya : ca-ES 대한민국 : ko-KR Chile : es-CL România : ro-RO Philippines : en-PH Latinoamérica : es- Canada : en-CA Singapore : en-SG India : en-IN New Zealand : en-NZ Svizzera : it-CH Canada : fr-CA भारत : hi-IN Danmark : da-DK Österreich : de-AT Brasil : pt-BR 中华人民共和国 : yue-CN 中国 : zh-CN Sverige : sv-SE भारत : hi-IN-translit España : es-ES Magyarország : hu-HU المملكة العربية السعودية : ar-SA Belgique : fr-BE United Kingdom : en-GB 日本 : ja-JP 香港（中國） : zh-HK Suomi : fi-FI Türkiye : tr-TR Norge : nb-NO Indonesia : en-ID Saudi Arabia : en-SA Polska : pl-PL Indonesia : id-ID Malaysia : ms-MY Ελλάδα : el-GR Česko : cs-CZ Hrvatska : hr-HR United Arab Emirates : en-AE ישראל : he-IL Россия : ru-RU China : wuu-CN Schweiz : de-CH Australia : en-AU Deutschland : de-DE België : nl-BE ไทย : th-TH Portugal : pt-PT Slovensko : sk-SK United States : en-US Ireland : en-IE Colombia : es-CO (null) : hi-Latn Україна : uk-UA Estados Unidos : es-US
> 
> Someone Could Update Android too.

**Comment by KhoiNguyen-281** [comment]
@jamsch 

Hi, thanks for your dedication with this library, I am having a problem with using react-native-voice when the internet is down. When my device is online, it worked fine with every language I selected, but after I turn off the internet, it worked for only english.
