### ISSUE TITLE
"Hey Google" Trigger

### ISSUE THREAD

**Issue by rajkissu** [wenkesj/react-native-voice#88]
I would like to trigger this library's speech recognition when a specific text is said, "Hey Google" for example.

How would I go about achieving this - is this possible with this library alone, or would I need to use another library to detect that voice action before using this for recognition?

**Comment by Noitidart** [comment]
This would be way aweome. Even awesomer, if it accepts it while app is in background.

**Comment by ohtangza** [comment]
Unfortunately, according to SO, you need to implement your own voice activation logic (https://stackoverflow.com/a/36720515/1609620). Please re-open it if there is further information.
