### ISSUE TITLE
is offline supported for iOS?

### ISSUE THREAD

**Issue by roycebranning** [wenkesj/react-native-voice#89]
Having trouble getting offline voice recognition to work on iOS. Everything works fine with internet access then don't get results when going offline.

Running it on iPhone 6SE.

Not sure what other details would be helpful to provide.

Thanks.

**Comment by ohtangza** [comment]
I just tested on my iPhone SE and found out Siri does not work offline. Usually, speech recognition with open text does not work well offline. Please let me know if there is a further inquiry.
