### ISSUE TITLE
Feature Request: Voice in background app

### ISSUE THREAD

**Issue by Deboracgs** [wenkesj/react-native-voice#9]
Hello, how do you make the implementation speech recognize the voice in the background? No need to push the button, and it recognizes key words

**Comment by wenkesj** [comment]
@Deboracgs That's an interesting question and I haven't really looked into it. This would probably have to involve a separate service that would call the `intent` from Android/iOS (and a lot of permissions work)!

**Comment by wenkesj** [comment]
I am going to close this, incase anyone wants to dive in at some point, this would be awesome!

**Comment by pixelcaliber** [comment]
@wenkesj hey, any update on this feature?
