### ISSUE TITLE
Undefined is not an object

### ISSUE THREAD

**Issue by jonnycraze** [wenkesj/react-native-voice#94]
I can't seem to shake this bug, and I can't figure what's wrong.

I followed the install instructions, and did the automatic linking, but when i try to call a library i get this error:

```TypeError: undefined is not an object (evaluating 'Voice.startSpeech')]```
This error is coming from within the library index.js file,
I set a console log here, and sure enough, Voice is undefined, what am I missing?

**Comment by jonnycraze** [comment]
The problem was starting with: create-react-native-app

If you build your app this way it cannot use native components like this.

Instead use react-native init

**Comment by ohtangza** [comment]
@jonnycraze Thanks for your update :)

**Comment by lfoliveir4** [comment]
![image](https://user-images.githubusercontent.com/32423942/56103773-d76bf900-5f0a-11e9-82ff-20a56914a6a9.png)

this error on Speech Recognition

**Comment by VivekSharma811** [comment]
I tried using react-native init as well. It didn't worked for me. Please help.
